### ISSUE TITLE
Pairing 

### ISSUE THREAD

**Issue by AbanobMedhat** [AbanobMedhat/GP2020#3]
## Pairing 
- Create new module to be imported in micro-python .

**Comment by a1h2med** [comment]
I've pushed some files which are fully working using C (provided by espressif) on esp32.
To run it you have to install the software development environment for the hardware based on the ESP32 chip by Espressif, but please make sure that YOU ARE NOT installing the last version, as for esp32(older versions) it works great using (Esp-IDF v4.0).
Also, make sure that you are selecting the right UUID (which you can easily get from your peripheral device OR from Bluetooth UUID standard page), as here I'm using UUID for ALERT_notification_system (0x1811), And you can easily change it from ble_cent.h file, setting it to whatever the UUID you are using.

**Comment by a1h2med** [comment]
I've pushed some edits in micropython code to allow pairing throw it.
Things to edit:
1- sysconfig addition.
2- Connect for encrypted services, and for not encrypted, as now I'm able to connect to ONLY encrypted services.
